import { useState } from 'react';
import './DataExport.css';

const DataExport = ({ data, locationName }) => {
  const [exportFormat, setExportFormat] = useState('json');
  const [showShareMenu, setShowShareMenu] = useState(false);

  const exportToJSON = () => {
    const jsonData = JSON.stringify(data, null, 2);
    const blob = new Blob([jsonData], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `weather-${locationName}-${new Date().toISOString().split('T')[0]}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportToCSV = () => {
    const csvRows = [];
    csvRows.push('Metric,Value,Unit');
    
    if (data) {
      csvRows.push(`Temperature,${data.temperature},°C`);
      csvRows.push(`Feels Like,${data.feels_like},°C`);
      csvRows.push(`Humidity,${data.humidity},%`);
      csvRows.push(`Pressure,${data.pressure},hPa`);
      csvRows.push(`Wind Speed,${data.wind_speed},m/s`);
      csvRows.push(`Conditions,${data.conditions},-`);
    }

    const csvContent = csvRows.join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `weather-${locationName}-${new Date().toISOString().split('T')[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const exportToPDF = () => {
    // Create a simple text-based PDF content
    const pdfContent = `
Weather Report - ${locationName}
Date: ${new Date().toLocaleString()}
=====================================

Temperature: ${data?.temperature}°C
Feels Like: ${data?.feels_like}°C
Humidity: ${data?.humidity}%
Pressure: ${data?.pressure} hPa
Wind Speed: ${data?.wind_speed} m/s
Conditions: ${data?.conditions}

Generated by Energy Conservation System
    `.trim();

    const blob = new Blob([pdfContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `weather-report-${locationName}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleExport = () => {
    switch (exportFormat) {
      case 'json':
        exportToJSON();
        break;
      case 'csv':
        exportToCSV();
        break;
      case 'pdf':
        exportToPDF();
        break;
      default:
        exportToJSON();
    }
  };

  const shareData = async (platform) => {
    const shareText = `Weather in ${locationName}: ${data?.temperature}°C, ${data?.conditions}`;
    const shareUrl = window.location.href;

    if (platform === 'native' && navigator.share) {
      try {
        await navigator.share({
          title: `Weather in ${locationName}`,
          text: shareText,
          url: shareUrl
        });
      } catch (error) {
        console.error('Error sharing:', error);
      }
    } else if (platform === 'twitter') {
      window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}&url=${encodeURIComponent(shareUrl)}`, '_blank');
    } else if (platform === 'facebook') {
      window.open(`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`, '_blank');
    } else if (platform === 'whatsapp') {
      window.open(`https://wa.me/?text=${encodeURIComponent(shareText + ' ' + shareUrl)}`, '_blank');
    } else if (platform === 'email') {
      window.location.href = `mailto:?subject=${encodeURIComponent(`Weather in ${locationName}`)}&body=${encodeURIComponent(shareText + '\n\n' + shareUrl)}`;
    } else if (platform === 'copy') {
      navigator.clipboard.writeText(shareText + '\n' + shareUrl);
      alert('Link copied to clipboard!');
    }

    setShowShareMenu(false);
  };

  if (!data) {
    return null;
  }

  return (
    <div className="data-export">
      <div className="export-section">
        <h3>📥 Export Data</h3>
        <div className="export-controls">
          <select 
            value={exportFormat} 
            onChange={(e) => setExportFormat(e.target.value)}
            className="format-select"
          >
            <option value="json">JSON Format</option>
            <option value="csv">CSV Format</option>
            <option value="pdf">Text Report</option>
          </select>
          <button onClick={handleExport} className="export-btn">
            📥 Download
          </button>
        </div>
      </div>

      <div className="share-section">
        <h3>🔗 Share</h3>
        <button 
          onClick={() => setShowShareMenu(!showShareMenu)}
          className="share-toggle-btn"
        >
          📤 Share Weather
        </button>

        {showShareMenu && (
          <div className="share-menu">
            {navigator.share && (
              <button onClick={() => shareData('native')} className="share-btn">
                📱 Share
              </button>
            )}
            <button onClick={() => shareData('twitter')} className="share-btn twitter">
              🐦 Twitter
            </button>
            <button onClick={() => shareData('facebook')} className="share-btn facebook">
              📘 Facebook
            </button>
            <button onClick={() => shareData('whatsapp')} className="share-btn whatsapp">
              💬 WhatsApp
            </button>
            <button onClick={() => shareData('email')} className="share-btn email">
              ✉️ Email
            </button>
            <button onClick={() => shareData('copy')} className="share-btn copy">
              📋 Copy Link
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default DataExport;
